# Generated by Django 4.1.7 on 2023-04-29 19:58

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("RecordLabel_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="djschedule",
            name="date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 4, 29)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="end_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 4, 29)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateField(
                validators=[
                    django.core.validators.MinValueValidator(
                        limit_value=datetime.date(2023, 4, 29)
                    )
                ]
            ),
        ),
        migrations.AlterField(
            model_name="eventfounder",
            name="phone",
            field=models.CharField(max_length=15),
        ),
    ]
