# Generated by Django 4.1.7 on 2023-03-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sneaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('color', models.CharField(max_length=50)),
                ('size', models.IntegerField()),
                ('price', models.IntegerField()),
                ('sole_tech', models.CharField(max_length=50)),
            ],
        ),
    ]
