# Generated by Django 4.1.7 on 2023-03-29 12:26

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0002_dj_djschedule_event_eventfounder_delete_sneaker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 29))]),
        ),
    ]
