# Generated by Django 4.1.7 on 2023-03-29 13:00

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0003_alter_event_start_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dj',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
        migrations.AlterField(
            model_name='djschedule',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 29))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 3, 29))]),
        ),
        migrations.AlterField(
            model_name='eventfounder',
            name='rating',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)]),
        ),
    ]
