# Generated by Django 4.1.7 on 2023-04-05 15:27

import datetime
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dj', '0004_alter_dj_rating_alter_djschedule_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djschedule',
            name='date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 4, 5))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='end_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 4, 5))]),
        ),
        migrations.AlterField(
            model_name='event',
            name='start_date',
            field=models.DateField(validators=[django.core.validators.MinValueValidator(limit_value=datetime.date(2023, 4, 5))]),
        ),
    ]
